# Generated by Django 4.2.6 on 2023-10-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_contact_alter_settings_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={},
        ),
        migrations.RemoveField(
            model_name='settings',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='linkeldin_url',
        ),
    ]
